name: foodlabelwiki
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  atlas_repo:
    path: packages/atlas_repo
  intl: ^0.18.0  
  bloc: ^8.1.2 # https://pub.dev/packages/flutter_bloc  
  equatable: ^2.0.5 # https://pub.dev/packages/equatable
  flutter_bloc: ^8.1.3 # https://pub.dev/packages/flutter_bloc
  go_router: ^7.1.1 # https://pub.dev/packages/go_router
  google_fonts: ^5.1.0 # https://pub.dev/packages/google_fonts

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  very_good_analysis: ^5.0.0+1 # https://pub.dev/packages/very_good_analysis/install

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
